repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Disabled mypy temporarily - enable when ready for strict type checking
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         - types-requests
  #         - types-redis
  #         - types-PyYAML
  #       args: [--ignore-missing-imports, --no-strict-optional]
  #       exclude: ^(tests/|migrations/)

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-quick
        entry: bash -c 'uv run pytest tests/test_config.py tests/test_agents.py tests/test_research_team.py -q'
        language: system
        pass_filenames: false
        always_run: false
        stages: [pre-commit]
